"use client";
import { FormEvent, useEffect, useRef, useState } from "react";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { ArrowLeft, Bot, Brain, Check, CheckCircle2, ChevronRight, ClipboardList, FileText, Globe2, History, LoaderCircle, MessageSquareText, MessagesSquare, PanelRight, Send, ShieldAlert, Sparkles, Upload, X } from "lucide-react";
import type { AgentRun, ArtifactVersion, ChangeProposal, MemoryItem, Message, ModelProfile, Project, Source } from "@pm-studio/core";
import { postProjectMessage } from "@/lib/message-request";
import { apiUrl } from "@/lib/app-path";
import { proposalChangeKey } from "@/lib/proposal-view";
import { questionForRun } from "@/lib/run-question";
import { readPmProposal } from "@/lib/pm-output";
import { PM_AGENT_NAME } from "@/lib/agents/catalog";

type Snapshot = { project: Project; baseline: ArtifactVersion; messages: Message[]; proposals: ChangeProposal[]; memories: MemoryItem[]; sources: Source[]; runs: AgentRun[]; models: ModelProfile[] };
const tabs = ["基线", "提案", "记忆", "来源", "轨迹"] as const;
const navItems = [
  { key: "chat", label: "持续对话", icon: MessageSquareText },
  { key: "assets", label: "产品资产", icon: FileText },
  { key: "decisions", label: "决策记录", icon: History }
] as const;
type View = typeof navItems[number]["key"];
export function Workspace({ initial, user }: { initial: Snapshot; user: { name: string; role: string } }) {
  const router = useRouter(); const [data, setData] = useState(initial); const [tab, setTab] = useState<typeof tabs[number]>("基线"); const [view, setView] = useState<View>("chat"); const [mobilePane, setMobilePane] = useState<"chat"|"context">("chat"); const [sending, setSending] = useState(false); const [sourceOpen, setSourceOpen] = useState(false); const [sourceMode, setSourceMode] = useState<"web"|"file"|"document"|"conversation">("web"); const [sourceBusy, setSourceBusy] = useState(false); const [notice, setNotice] = useState(""); const [correctingMemoryId, setCorrectingMemoryId] = useState<string | null>(null); const [correction, setCorrection] = useState(""); const messageListRef = useRef<HTMLDivElement>(null);
  async function refresh() { const response = await fetch(apiUrl(`/api/projects/${data.project.id}`), { cache: "no-store" }); if (response.ok) setData(await response.json()); }
  function scrollMessages() { const list = messageListRef.current; if (list) list.scrollTop = list.scrollHeight; }
  function openPane(target: "chat"|"context") { setView("chat"); setMobilePane(target); }
  async function send(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = event.currentTarget; const input = new FormData(form).get("message"); if (typeof input !== "string" || !input.trim() || sending) return; setNotice(""); setSending(true); const result = await postProjectMessage(fetch, data.project.id, input); if (!result.ok) { setNotice(result.error); setSending(false); return; } form.reset(); try { await refresh(); setTimeout(scrollMessages, 20); } catch { setNotice("消息已提交，但刷新失败，请刷新页面确认结果。"); } finally { setSending(false); } }
  async function proposalAction(id: string, action: "accept"|"reject") { setNotice(""); const response = await fetch(apiUrl(`/api/proposals/${id}`), { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ action }) }); if (!response.ok) setNotice((await response.json().catch(() => ({}))).error || "提案处理失败"); await refresh(); router.refresh(); }
  async function memoryAction(id: string, action: "confirm"|"forget"|"correct", content?: string) { setNotice(""); const response = await fetch(apiUrl(`/api/memories/${id}`), { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ action, content }) }); if (!response.ok) setNotice((await response.json().catch(() => ({}))).error || "记忆处理失败"); else { setCorrectingMemoryId(null); setCorrection(""); } await refresh(); }
  async function addSource(event: FormEvent<HTMLFormElement>) {
    event.preventDefault();
    const form = event.currentTarget;
    const fields = new FormData(form);
    setNotice(""); setSourceBusy(true);
    let response: Response;
    if (sourceMode === "file") {
      const payload = new FormData();
      const file = fields.get("file");
      if (!(file instanceof File) || !file.size) { setNotice("请选择要上传的文件"); setSourceBusy(false); return; }
      payload.set("file", file);
      response = await fetch(apiUrl(`/api/projects/${data.project.id}/sources`), { method: "POST", body: payload });
    } else if (sourceMode === "document" || sourceMode === "conversation") {
      response = await fetch(apiUrl(`/api/projects/${data.project.id}/sources`), { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ mode: sourceMode, title: fields.get("title"), content: fields.get("content") }) });
    } else {
      response = await fetch(apiUrl(`/api/projects/${data.project.id}/sources`), { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ url: fields.get("url"), title: fields.get("title") }) });
    }
    if (!response.ok) setNotice((await response.json().catch(() => ({}))).error || "来源处理失败");
    else { form.reset(); setSourceOpen(false); await refresh(); }
    setSourceBusy(false);
  }
  async function deleteSource(id: string) { setNotice(""); const response = await fetch(apiUrl(`/api/projects/${data.project.id}/sources/${id}`), { method: "DELETE" }); if (!response.ok) setNotice((await response.json().catch(() => ({}))).error || "来源删除失败"); await refresh(); }
  useEffect(() => { scrollMessages(); }, []);
  const canEdit = user.role !== "reviewer"; const demoMode = !data.models.some((model) => model.provider === "openai" && model.configured); const b = data.baseline.baseline;
  const pendingCount = data.proposals.filter((p) => p.status === "pending").length;
  const tabsRow = <div className="context-tabs">{tabs.map((item) => <button key={item} className={tab === item ? "active" : ""} onClick={() => setTab(item)}>{item}{item === "提案" && pendingCount > 0 && <i>{pendingCount}</i>}</button>)}</div>;
  const contextBody = <>{notice && <p className="context-notice" role="alert">{notice}</p>}{tab === "基线" && <><div className="context-heading"><div><p className="eyebrow">正式版本</p><h2>产品基线 v{data.baseline.version}</h2></div><CheckCircle2 size={20}/></div><BaselineSection title="产品摘要" content={b.summary}/><BaselineSection title="核心问题" content={b.problem}/><BaselineList title="目标" items={b.goals}/><BaselineList title="范围" items={b.scope}/><BaselineList title="关键需求" items={b.requirements}/><BaselineList title="风险" items={b.risks} tone="risk"/><BaselineList title="开放问题" items={b.openQuestions} tone="question"/></>}
  {tab === "提案" && <><div className="context-heading"><div><p className="eyebrow">人工审批</p><h2>候选变更</h2></div></div>{data.proposals.length === 0 && <p className="context-empty">还没有候选提案。对话中产生的变更会先出现在这里等待审批。</p>}{data.proposals.map((proposal) => <div className="proposal" key={proposal.id}><header><span className={`proposal-status ${proposal.status}`}>{proposalStatusLabel(proposal.status)}</span><h3>{proposal.title}</h3><p>{proposal.rationale}</p></header>{proposal.changes.map((change, index) => <div className="diff" key={proposalChangeKey(proposal.id, change.path, index)}><code>{change.path}</code><span>+</span><p>{String(change.after)}</p></div>)}{proposal.status === "pending" && canEdit && <footer><button className="secondary-button danger" onClick={() => proposalAction(proposal.id,"reject")}><X size={15}/>拒绝</button><button className="primary-button compact" onClick={() => proposalAction(proposal.id,"accept")}><Check size={15}/>批准并创建新版本</button></footer>}</div>)}</>}
  {tab === "记忆" && <><div className="context-heading"><div><p className="eyebrow">分层记忆</p><h2>产品事实与约束</h2></div></div>{data.memories.length === 0 && <p className="context-empty">暂无记忆。对话中被识别的产品事实和约束会出现在这里。</p>}{data.memories.map((memory) => <div className="memory-row" key={memory.id}><div className={`memory-icon ${memory.status}`}><Brain size={16}/></div><div><header><span>{memory.type}</span><b>{Math.round(memory.confidence*100)}%</b></header><p>{memory.content}</p><small>{memory.status} · {memory.sourceMessageIds.length} 个来源</small>{correctingMemoryId === memory.id && <form className="memory-correction" onSubmit={(event) => { event.preventDefault(); if (correction.trim()) memoryAction(memory.id,"correct",correction.trim()); }}><textarea value={correction} onChange={(event) => setCorrection(event.target.value)} rows={3} autoFocus/><div><button type="button" onClick={() => { setCorrectingMemoryId(null); setCorrection(""); }}>取消</button><button>确认纠正</button></div></form>}{memory.status === "candidate" && canEdit && correctingMemoryId !== memory.id && <div className="inline-actions"><button onClick={()=>memoryAction(memory.id,"forget")}>{memory.type === "conflict" ? "保留原记忆" : "忽略"}</button><button onClick={() => { setCorrectingMemoryId(memory.id); setCorrection(memory.type === "conflict" ? "" : memory.content); }}>纠正</button>{memory.type !== "conflict" && <button onClick={()=>memoryAction(memory.id,"confirm")}>确认记忆</button>}</div>}</div></div>)}</>}
  {tab === "来源" && <><div className="context-heading"><div><p className="eyebrow">知识依据 · 文档 / 材料 / 对话</p><h2>历史资料库</h2></div>{canEdit && <button className="icon-button" title="导入资料" aria-label="导入资料" onClick={() => setSourceOpen((value) => !value)}><Upload size={17}/></button>}</div>{sourceOpen && <form className="source-add" onSubmit={addSource}><div className="source-mode"><button type="button" className={sourceMode === "web" ? "active" : ""} onClick={() => setSourceMode("web")}><Globe2 size={14}/>网页</button><button type="button" className={sourceMode === "file" ? "active" : ""} onClick={() => setSourceMode("file")}><FileText size={14}/>文档</button><button type="button" className={sourceMode === "document" ? "active" : ""} onClick={() => setSourceMode("document")}><ClipboardList size={14}/>材料</button><button type="button" className={sourceMode === "conversation" ? "active" : ""} onClick={() => setSourceMode("conversation")}><MessagesSquare size={14}/>对话</button></div>{sourceMode === "web" ? <><label>网页地址<input name="url" type="url" placeholder="https://example.com/spec" required/></label><label>来源名称（可选）<input name="title" placeholder="产品规范"/></label></> : sourceMode === "file" ? <label>选择文档（PDF / DOCX / TXT / MD / CSV，全文解析）<input name="file" type="file" accept=".pdf,.docx,.txt,.md,.markdown,.csv,.json,.log,.html,.xml" required/></label> : <><label>{sourceMode === "conversation" ? "对话名称" : "材料标题"}<input name="title" placeholder={sourceMode === "conversation" ? "客户访谈记录 0812" : "竞品调研笔记"} required/></label><label>{sourceMode === "conversation" ? "粘贴历史对话全文" : "粘贴材料正文"}<textarea name="content" rows={7} placeholder={sourceMode === "conversation" ? "直接粘贴聊天记录、会议纪要或访谈对话，支持任意格式" : "粘贴需求文档、会议纪要、调研笔记等文本材料"} required/></label></>}<div className="source-actions"><button type="button" className="secondary-button" onClick={() => setSourceOpen(false)}>取消</button><button className="primary-button compact" disabled={sourceBusy}>{sourceBusy ? "解析中..." : "加入知识库"}</button></div></form>}{data.sources.length === 0 && <p className="context-empty">资料库还是空的。把历史文档、粘贴材料和对话记录全部丢进来，AI 产品经理会在每轮讨论中检索引用它们。</p>}{data.sources.map((source) => <div className="source-row" key={source.id}>{source.kind === "web" ? <Globe2/> : source.kind === "conversation" ? <MessagesSquare/> : <FileText/>}<div><h3>{source.title}</h3><p>{source.excerpt}</p>{typeof source.charCount === "number" && <small className="source-meta">已解析全文 {source.charCount} 字 · 可被 AI 检索引用</small>}{source.content && <details className="source-reader"><summary>阅读全文</summary><p>{source.content.length > 20000 ? `${source.content.slice(0, 20000)}\n…[预览已截断，全文 ${source.charCount || source.content.length} 字]` : source.content}</p></details>}{source.url && <a href={source.url} target="_blank" rel="noreferrer">打开原始来源</a>}{canEdit && <button className="source-delete" onClick={() => deleteSource(source.id)}>删除</button>}</div></div>)}</>}
  {tab === "轨迹" && <><div className="context-heading"><div><p className="eyebrow">可审计运行</p><h2>Agent 协作轨迹</h2></div></div>{data.runs.length === 0 && <p className="context-empty">暂无运行记录。发送第一条对话后，这里会展示专家协作轨迹。</p>}{data.runs.map((run) => <div className="run-block" key={run.id}><header><span className="run-question" title={questionForRun(data.messages, run.id)}>{questionForRun(data.messages, run.id)}</span><b>{run.demoMode ? "演示路由" : "真实模型"} · {(run.durationMs/1000).toFixed(1)}s</b></header>{run.steps.map((step, index) => <div className="step-row" key={step.id}><div className="step-line"><i/><span>{index+1}</span></div><div><header><strong>{step.agent}</strong><small>{step.provider} · {step.model}</small></header><p>{step.summary}</p>{step.agent === PM_AGENT_NAME && <PmTraceOutput output={step.output}/>}</div></div>)}</div>)}</>}</>;
  return <div className="workspace-shell">
    <header className="workspace-header"><Link href="/" className="icon-button"><ArrowLeft size={18}/></Link><div className="workspace-title"><h1>{data.project.name}</h1><span>基线 v{data.project.baselineVersion}</span></div><div className="header-status"><span className="status-dot"/>系统正常</div></header>
    <nav className="mobile-switch"><button className={view === "chat" && mobilePane === "chat" ? "active" : ""} onClick={() => openPane("chat")}><MessageSquareText size={16}/>对话</button><button className={view === "chat" && mobilePane === "context" ? "active" : ""} onClick={() => openPane("context")}><PanelRight size={16}/>产品上下文</button><button className={view === "assets" ? "active" : ""} onClick={() => setView("assets")}><FileText size={16}/>资产</button><button className={view === "decisions" ? "active" : ""} onClick={() => setView("decisions")}><History size={16}/>决策</button></nav>
    <div className={`workspace-grid ${view !== "chat" ? "wide" : ""}`}>
      <aside className="project-nav"><div className="nav-section"><span>工作区</span>{navItems.map((item) => <button key={item.key} className={view === item.key ? "active" : ""} onClick={() => setView(item.key)}><item.icon/>{item.label}</button>)}</div><div className="nav-section"><span>状态</span><div className="compact-stat"><b>{data.project.pendingProposals}</b> 待审批提案</div><div className="compact-stat"><b>{data.project.openQuestions}</b> 开放问题</div></div><div className="model-health"><span>模型路由</span>{data.models.map((model) => <div key={model.id}><i className={model.configured ? "online" : "demo"}/><p>{model.role}<small>{model.configured ? model.model : "Demo 回退"}</small></p></div>)}</div></aside>
      {view === "chat" ? <main className={`conversation ${mobilePane !== "chat" ? "mobile-hidden" : ""}`}><div className="conversation-head"><div><p className="eyebrow">统一 PM</p><h2>产品打磨对话</h2></div><span className="demo-badge">{demoMode ? "DEMO MODE" : "LIVE MODE"}</span></div>
        <div className="message-list" ref={messageListRef}>{data.messages.map((message) => <article key={message.id} className={`message ${message.role}`}><div className="avatar">{message.role === "assistant" ? <Sparkles size={17}/> : user.name.slice(0,1)}</div><div><header><strong>{message.author}</strong><time>{new Date(message.createdAt).toLocaleTimeString("zh-CN", { hour: "2-digit", minute: "2-digit" })}</time></header><p>{message.content}</p>{message.citations.length > 0 && <div className="message-citations">{message.citations.map((citation) => { const source = data.sources.find((item) => item.id === citation); return <button key={citation} onClick={() => { setTab("来源"); openPane("context"); }}><FileText size={12}/>{source?.title || citation}</button>; })}</div>}{message.runId && <button className="trace-link" onClick={() => { setTab("轨迹"); openPane("context"); }}><Bot size={14}/>查看专家协作轨迹<ChevronRight size={14}/></button>}</div></article>)}{sending && <article className="message assistant"><div className="avatar"><LoaderCircle className="spin" size={17}/></div><div><header><strong>AI 产品经理</strong></header><p>正在调度需求、领域、规划和批判评审专家...</p></div></article>}</div>
        <form className="composer" onSubmit={send}><textarea name="message" placeholder={canEdit ? "继续描述产品、纠正理解，或要求拆分功能..." : "提出评审意见或修改建议..."} rows={3} disabled={sending} onKeyDown={(event) => { if (event.key === "Enter" && !event.shiftKey) { event.preventDefault(); event.currentTarget.form?.requestSubmit(); } }}/><div><span>正式资产将在审批后更新</span><button className="send-button" disabled={sending} title="发送"><Send size={18}/></button></div></form>
      </main> : <main className="conversation asset-view"><div className="conversation-head"><div><p className="eyebrow">{view === "assets" ? "基线 · 提案 · 记忆 · 来源 · 轨迹" : "方向与审批留痕"}</p><h2>{view === "assets" ? "产品资产" : "决策记录"}</h2></div><span className="demo-badge">{demoMode ? "DEMO MODE" : "LIVE MODE"}</span></div>
        <div className="asset-canvas">{view === "assets" ? <>{tabsRow}<div className="context-content">{contextBody}</div></> : <DecisionsView decisions={b.decisions} proposals={data.proposals}/>}</div>
      </main>}
      {view === "chat" && <aside className={`context-panel ${mobilePane !== "context" ? "mobile-hidden" : ""}`}>{tabsRow}<div className="context-content">{contextBody}</div></aside>}
    </div>
  </div>;
}
function proposalStatusLabel(status: ChangeProposal["status"]) {
  if (status === "accepted") return "已批准";
  if (status === "rejected") return "已拒绝";
  if (status === "stale") return "已过期";
  return "待审批";
}
function BaselineSection({ title, content }: { title: string; content: string }) { return <section className="baseline-section"><h3>{title}</h3><p>{content}</p></section>; }
function BaselineList({ title, items, tone = "default" }: { title: string; items: string[]; tone?: string }) { return <section className="baseline-section"><h3>{title}</h3><ul className={tone}>{items.map((item) => <li key={item}>{tone === "risk" ? <ShieldAlert size={14}/> : <i/>}<span>{item}</span></li>)}</ul></section>; }
function DecisionsView({ decisions, proposals }: { decisions: string[]; proposals: ChangeProposal[] }) {
  const reviewed = proposals.filter((proposal) => proposal.status === "accepted" || proposal.status === "rejected");
  return <div className="context-content">
    <div className="context-heading"><div><p className="eyebrow">已确认方向</p><h2>关键产品决策</h2></div><History size={20}/></div>
    {decisions.length === 0 ? <p className="context-empty">基线中还没有记录关键决策。</p> : <section className="baseline-section"><ul>{decisions.map((item) => <li key={item}><i/><span>{item}</span></li>)}</ul></section>}
    <div className="context-heading decisions-heading"><div><p className="eyebrow">审批留痕</p><h2>提案处理记录</h2></div></div>
    {reviewed.length === 0 ? <p className="context-empty">暂无审批记录。在「提案」中批准或拒绝候选变更后会在这里留痕。</p> : reviewed.map((proposal) => <div className="proposal" key={proposal.id}><header><span className={`proposal-status ${proposal.status}`}>{proposalStatusLabel(proposal.status)}</span><h3>{proposal.title}</h3><p>{proposal.rationale}</p></header><footer className="decision-meta"><span>基于基线 v{proposal.baseVersion} · {proposal.reviewedAt ? new Date(proposal.reviewedAt).toLocaleString("zh-CN", { hour12: false }) : "审批时间未知"}</span></footer></div>)}
  </div>;
}
function PmTraceOutput({ output }: { output: unknown }) {
  const proposal = readPmProposal(output);
  if (!proposal) return null;
  return <div className="pm-trace-output"><strong>PM 提案整理：{proposal.title}</strong><p>{proposal.rationale}</p>{proposal.items.map((item, index) => <div key={`${item.category}:${index}`}><code>{item.category}</code><span>{item.content}</span></div>)}</div>;
}
