"use client";
import { FormEvent, useEffect, useRef, useState } from "react";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { ArrowLeft, Bot, Brain, Check, CheckCircle2, ChevronRight, FileText, Globe2, History, LoaderCircle, MessageSquareText, PanelRight, Send, ShieldAlert, Sparkles, Upload, X } from "lucide-react";
import type { AgentRun, ArtifactVersion, ChangeProposal, MemoryItem, Message, ModelProfile, Project, Source } from "@pm-studio/core";
import { postProjectMessage } from "@/lib/message-request";
import { proposalChangeKey } from "@/lib/proposal-view";
import { questionForRun } from "@/lib/run-question";
import { readPmProposal } from "@/lib/pm-output-view";
import { PM_AGENT_NAME } from "@/lib/agents/catalog";

type Snapshot = { project: Project; baseline: ArtifactVersion; messages: Message[]; proposals: ChangeProposal[]; memories: MemoryItem[]; sources: Source[]; runs: AgentRun[]; models: ModelProfile[] };
const tabs = ["基线", "提案", "记忆", "来源", "轨迹"] as const;
export function Workspace({ initial, user }: { initial: Snapshot; user: { name: string; role: string } }) {
  const router = useRouter(); const [data, setData] = useState(initial); const [tab, setTab] = useState<typeof tabs[number]>("基线"); const [mobilePane, setMobilePane] = useState<"chat"|"context">("chat"); const [sending, setSending] = useState(false); const [sourceOpen, setSourceOpen] = useState(false); const [sourceMode, setSourceMode] = useState<"web"|"file">("web"); const [sourceBusy, setSourceBusy] = useState(false); const [notice, setNotice] = useState(""); const [correctingMemoryId, setCorrectingMemoryId] = useState<string | null>(null); const [correction, setCorrection] = useState(""); const messageListRef = useRef<HTMLDivElement>(null);
  async function refresh() { const response = await fetch(`/api/projects/${data.project.id}`, { cache: "no-store" }); if (response.ok) setData(await response.json()); }
  function scrollMessages() { const list = messageListRef.current; if (list) list.scrollTop = list.scrollHeight; }
  async function send(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = event.currentTarget; const input = new FormData(form).get("message"); if (typeof input !== "string" || !input.trim() || sending) return; setNotice(""); setSending(true); const result = await postProjectMessage(fetch, data.project.id, input); if (!result.ok) { setNotice(result.error); setSending(false); return; } form.reset(); try { await refresh(); setTimeout(scrollMessages, 20); } catch { setNotice("消息已提交，但刷新失败，请刷新页面确认结果。"); } finally { setSending(false); } }
  async function proposalAction(id: string, action: "accept"|"reject") { setNotice(""); const response = await fetch(`/api/proposals/${id}`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ action }) }); if (!response.ok) setNotice((await response.json().catch(() => ({}))).error || "提案处理失败"); await refresh(); router.refresh(); }
  async function memoryAction(id: string, action: "confirm"|"forget"|"correct", content?: string) { setNotice(""); const response = await fetch(`/api/memories/${id}`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ action, content }) }); if (!response.ok) setNotice((await response.json().catch(() => ({}))).error || "记忆处理失败"); else { setCorrectingMemoryId(null); setCorrection(""); } await refresh(); }
  async function addSource(event: FormEvent<HTMLFormElement>) {
    event.preventDefault();
    const form = event.currentTarget;
    const fields = new FormData(form);
    setNotice(""); setSourceBusy(true);
    let response: Response;
    if (sourceMode === "file") {
      const payload = new FormData();
      const file = fields.get("file");
      if (!(file instanceof File) || !file.size) { setNotice("请选择要上传的文件"); setSourceBusy(false); return; }
      payload.set("file", file);
      response = await fetch(`/api/projects/${data.project.id}/sources`, { method: "POST", body: payload });
    } else {
      response = await fetch(`/api/projects/${data.project.id}/sources`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ url: fields.get("url"), title: fields.get("title") }) });
    }
    if (!response.ok) setNotice((await response.json().catch(() => ({}))).error || "来源处理失败");
    else { form.reset(); setSourceOpen(false); await refresh(); }
    setSourceBusy(false);
  }
  useEffect(() => { scrollMessages(); }, []);
  const canEdit = user.role !== "reviewer"; const demoMode = !data.models.some((model) => model.provider === "openai" && model.configured); const b = data.baseline.baseline;
  return <div className="workspace-shell">
    <header className="workspace-header"><Link href="/" className="icon-button"><ArrowLeft size={18}/></Link><div className="workspace-title"><h1>{data.project.name}</h1><span>基线 v{data.project.baselineVersion}</span></div><div className="header-status"><span className="status-dot"/>系统正常</div></header>
    <nav className="mobile-switch"><button className={mobilePane === "chat" ? "active" : ""} onClick={() => setMobilePane("chat")}><MessageSquareText size={16}/>对话</button><button className={mobilePane === "context" ? "active" : ""} onClick={() => setMobilePane("context")}><PanelRight size={16}/>产品上下文</button></nav>
    <div className="workspace-grid">
      <aside className="project-nav"><div className="nav-section"><span>工作区</span><button className="active"><MessageSquareText/>持续对话</button><button><FileText/>产品资产</button><button><History/>决策记录</button></div><div className="nav-section"><span>状态</span><div className="compact-stat"><b>{data.project.pendingProposals}</b> 待审批提案</div><div className="compact-stat"><b>{data.project.openQuestions}</b> 开放问题</div></div><div className="model-health"><span>模型路由</span>{data.models.map((model) => <div key={model.id}><i className={model.configured ? "online" : "demo"}/><p>{model.role}<small>{model.configured ? model.model : "Demo 回退"}</small></p></div>)}</div></aside>
      <main className={`conversation ${mobilePane !== "chat" ? "mobile-hidden" : ""}`}><div className="conversation-head"><div><p className="eyebrow">统一 PM</p><h2>产品打磨对话</h2></div><span className="demo-badge">{demoMode ? "DEMO MODE" : "LIVE MODE"}</span></div>
        <div className="message-list" ref={messageListRef}>{data.messages.map((message) => <article key={message.id} className={`message ${message.role}`}><div className="avatar">{message.role === "assistant" ? <Sparkles size={17}/> : user.name.slice(0,1)}</div><div><header><strong>{message.author}</strong><time>{new Date(message.createdAt).toLocaleTimeString("zh-CN", { hour: "2-digit", minute: "2-digit" })}</time></header><p>{message.content}</p>{message.citations.length > 0 && <div className="message-citations">{message.citations.map((citation) => { const source = data.sources.find((item) => item.id === citation); return <button key={citation} onClick={() => { setTab("来源"); setMobilePane("context"); }}><FileText size={12}/>{source?.title || citation}</button>; })}</div>}{message.runId && <button className="trace-link" onClick={() => { setTab("轨迹"); setMobilePane("context"); }}><Bot size={14}/>查看专家协作轨迹<ChevronRight size={14}/></button>}</div></article>)}{sending && <article className="message assistant"><div className="avatar"><LoaderCircle className="spin" size={17}/></div><div><header><strong>AI 产品经理</strong></header><p>正在调度需求、领域、规划和批判评审专家...</p></div></article>}</div>
        <form className="composer" onSubmit={send}><textarea name="message" placeholder={canEdit ? "继续描述产品、纠正理解，或要求拆分功能..." : "提出评审意见或修改建议..."} rows={3} disabled={sending} onKeyDown={(event) => { if (event.key === "Enter" && !event.shiftKey) { event.preventDefault(); event.currentTarget.form?.requestSubmit(); } }}/><div><span>正式资产将在审批后更新</span><button className="send-button" disabled={sending} title="发送"><Send size={18}/></button></div></form>
      </main>
      <aside className={`context-panel ${mobilePane !== "context" ? "mobile-hidden" : ""}`}><div className="context-tabs">{tabs.map((item) => <button key={item} className={tab === item ? "active" : ""} onClick={() => setTab(item)}>{item}{item === "提案" && data.proposals.filter(p=>p.status==="pending").length > 0 && <i>{data.proposals.filter(p=>p.status==="pending").length}</i>}</button>)}</div>
        <div className="context-content">{notice && <p className="context-notice" role="alert">{notice}</p>}{tab === "基线" && <><div className="context-heading"><div><p className="eyebrow">正式版本</p><h2>产品基线 v{data.baseline.version}</h2></div><CheckCircle2 size={20}/></div><BaselineSection title="产品摘要" content={b.summary}/><BaselineSection title="核心问题" content={b.problem}/><BaselineList title="目标" items={b.goals}/><BaselineList title="范围" items={b.scope}/><BaselineList title="关键需求" items={b.requirements}/><BaselineList title="风险" items={b.risks} tone="risk"/><BaselineList title="开放问题" items={b.openQuestions} tone="question"/></>}
        {tab === "提案" && <><div className="context-heading"><div><p className="eyebrow">人工审批</p><h2>候选变更</h2></div></div>{data.proposals.map((proposal) => <div className="proposal" key={proposal.id}><header><span className={`proposal-status ${proposal.status}`}>{proposal.status}</span><h3>{proposal.title}</h3><p>{proposal.rationale}</p></header>{proposal.changes.map((change, index) => <div className="diff" key={proposalChangeKey(proposal.id, change.path, index)}><code>{change.path}</code><span>+</span><p>{String(change.after)}</p></div>)}{proposal.status === "pending" && canEdit && <footer><button className="secondary-button danger" onClick={() => proposalAction(proposal.id,"reject")}><X size={15}/>拒绝</button><button className="primary-button compact" onClick={() => proposalAction(proposal.id,"accept")}><Check size={15}/>批准并创建新版本</button></footer>}</div>)}</>}
        {tab === "记忆" && <><div className="context-heading"><div><p className="eyebrow">分层记忆</p><h2>产品事实与约束</h2></div></div>{data.memories.map((memory) => <div className="memory-row" key={memory.id}><div className={`memory-icon ${memory.status}`}><Brain size={16}/></div><div><header><span>{memory.type}</span><b>{Math.round(memory.confidence*100)}%</b></header><p>{memory.content}</p><small>{memory.status} · {memory.sourceMessageIds.length} 个来源</small>{correctingMemoryId === memory.id && <form className="memory-correction" onSubmit={(event) => { event.preventDefault(); if (correction.trim()) memoryAction(memory.id,"correct",correction.trim()); }}><textarea value={correction} onChange={(event) => setCorrection(event.target.value)} rows={3} autoFocus/><div><button type="button" onClick={() => { setCorrectingMemoryId(null); setCorrection(""); }}>取消</button><button>确认纠正</button></div></form>}{memory.status === "candidate" && canEdit && correctingMemoryId !== memory.id && <div className="inline-actions"><button onClick={()=>memoryAction(memory.id,"forget")}>{memory.type === "conflict" ? "保留原记忆" : "忽略"}</button><button onClick={() => { setCorrectingMemoryId(memory.id); setCorrection(memory.type === "conflict" ? "" : memory.content); }}>纠正</button>{memory.type !== "conflict" && <button onClick={()=>memoryAction(memory.id,"confirm")}>确认记忆</button>}</div>}</div></div>)}</>}
        {tab === "来源" && <><div className="context-heading"><div><p className="eyebrow">知识依据</p><h2>文件与网页</h2></div>{canEdit && <button className="icon-button" title="添加来源" aria-label="添加来源" onClick={() => setSourceOpen((value) => !value)}><Upload size={17}/></button>}</div>{sourceOpen && <form className="source-add" onSubmit={addSource}><div className="source-mode"><button type="button" className={sourceMode === "web" ? "active" : ""} onClick={() => setSourceMode("web")}><Globe2 size={14}/>网页</button><button type="button" className={sourceMode === "file" ? "active" : ""} onClick={() => setSourceMode("file")}><FileText size={14}/>文件</button></div>{sourceMode === "web" ? <><label>网页地址<input name="url" type="url" placeholder="https://example.com/spec" required/></label><label>来源名称（可选）<input name="title" placeholder="产品规范"/></label></> : <label>选择资料<input name="file" type="file" accept=".pdf,.docx,.pptx,.xlsx,.md,.txt,.csv,image/*" required/></label>}<div className="source-actions"><button type="button" className="secondary-button" onClick={() => setSourceOpen(false)}>取消</button><button className="primary-button compact" disabled={sourceBusy}>{sourceBusy ? "处理中..." : "加入知识库"}</button></div></form>}{data.sources.map((source) => <div className="source-row" key={source.id}>{source.kind === "web" ? <Globe2/> : <FileText/>}<div><h3>{source.title}</h3><p>{source.excerpt}</p>{source.url && <a href={source.url} target="_blank" rel="noreferrer">打开原始来源</a>}</div></div>)}</>}
        {tab === "轨迹" && <><div className="context-heading"><div><p className="eyebrow">可审计运行</p><h2>Agent 协作轨迹</h2></div></div>{data.runs.map((run) => <div className="run-block" key={run.id}><header><span className="run-question" title={questionForRun(data.messages, run.id)}>{questionForRun(data.messages, run.id)}</span><b>{run.demoMode ? "演示路由" : "真实模型"} · {(run.durationMs/1000).toFixed(1)}s</b></header>{run.steps.map((step, index) => <div className="step-row" key={step.id}><div className="step-line"><i/><span>{index+1}</span></div><div><header><strong>{step.agent}</strong><small>{step.provider} · {step.model}</small></header><p>{step.summary}</p>{step.agent === PM_AGENT_NAME && <PmTraceOutput output={step.output}/>}</div></div>)}</div>)}</>}</div>
      </aside>
    </div>
  </div>;
}
function BaselineSection({ title, content }: { title: string; content: string }) { return <section className="baseline-section"><h3>{title}</h3><p>{content}</p></section>; }
function BaselineList({ title, items, tone = "default" }: { title: string; items: string[]; tone?: string }) { return <section className="baseline-section"><h3>{title}</h3><ul className={tone}>{items.map((item) => <li key={item}>{tone === "risk" ? <ShieldAlert size={14}/> : <i/>}<span>{item}</span></li>)}</ul></section>; }
function PmTraceOutput({ output }: { output: unknown }) {
  const proposal = readPmProposal(output);
  if (!proposal) return null;
  return <div className="pm-trace-output"><strong>PM 提案整理：{proposal.title}</strong><p>{proposal.rationale}</p>{proposal.items.map((item, index) => <div key={`${item.category}:${index}`}><code>{item.category}</code><span>{item.content}</span></div>)}</div>;
}
