CREATE EXTENSION IF NOT EXISTS vector;
CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE TABLE IF NOT EXISTS users (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), username text UNIQUE NOT NULL, name text NOT NULL, role text NOT NULL CHECK (role IN ('admin','editor','reviewer')), password_hash text NOT NULL, must_change_password boolean NOT NULL DEFAULT true, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS projects (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), name text NOT NULL, description text NOT NULL, stage text NOT NULL, language text NOT NULL DEFAULT 'zh-CN', baseline_version integer NOT NULL DEFAULT 1, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS conversations (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), project_id uuid NOT NULL REFERENCES projects(id), created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS messages (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), conversation_id uuid NOT NULL REFERENCES conversations(id), role text NOT NULL, author text NOT NULL, content text NOT NULL, citations jsonb NOT NULL DEFAULT '[]', run_id uuid, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS agent_runs (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), project_id uuid NOT NULL REFERENCES projects(id), status text NOT NULL, demo_mode boolean NOT NULL DEFAULT false, cost_usd numeric(12,6) NOT NULL DEFAULT 0, duration_ms integer NOT NULL DEFAULT 0, created_at timestamptz NOT NULL DEFAULT now(), completed_at timestamptz);
CREATE TABLE IF NOT EXISTS agent_steps (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), run_id uuid NOT NULL REFERENCES agent_runs(id), agent text NOT NULL, provider text NOT NULL, model text NOT NULL, status text NOT NULL, summary text NOT NULL, duration_ms integer NOT NULL DEFAULT 0, retries integer NOT NULL DEFAULT 0, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS artifact_versions (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), project_id uuid NOT NULL REFERENCES projects(id), version integer NOT NULL, baseline jsonb NOT NULL, created_by uuid REFERENCES users(id), created_at timestamptz NOT NULL DEFAULT now(), UNIQUE(project_id, version));
CREATE TABLE IF NOT EXISTS change_proposals (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), project_id uuid NOT NULL REFERENCES projects(id), base_version integer NOT NULL, title text NOT NULL, rationale text NOT NULL, status text NOT NULL, changes jsonb NOT NULL, run_id uuid REFERENCES agent_runs(id), created_at timestamptz NOT NULL DEFAULT now(), reviewed_at timestamptz);
CREATE TABLE IF NOT EXISTS memory_items (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), project_id uuid NOT NULL REFERENCES projects(id), type text NOT NULL, content text NOT NULL, confidence real NOT NULL, status text NOT NULL, source_message_ids jsonb NOT NULL DEFAULT '[]', supersedes_id uuid REFERENCES memory_items(id), valid_until timestamptz, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS sources (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), project_id uuid NOT NULL REFERENCES projects(id), kind text NOT NULL, title text NOT NULL, url text, mime_type text, status text NOT NULL, excerpt text NOT NULL DEFAULT '', object_key text, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS source_chunks (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), source_id uuid NOT NULL REFERENCES sources(id), content text NOT NULL, location jsonb NOT NULL DEFAULT '{}', embedding vector(1536));
CREATE TABLE IF NOT EXISTS prompt_versions (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), area text NOT NULL, version integer NOT NULL, content text NOT NULL, status text NOT NULL, created_at timestamptz NOT NULL DEFAULT now(), UNIQUE(area, version));
CREATE TABLE IF NOT EXISTS evolution_proposals (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), prompt_area text NOT NULL, status text NOT NULL, metrics jsonb NOT NULL, change_summary text NOT NULL, created_at timestamptz NOT NULL DEFAULT now(), published_at timestamptz);
CREATE TABLE IF NOT EXISTS audit_events (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), actor_id uuid REFERENCES users(id), action text NOT NULL, target text NOT NULL, detail text NOT NULL, created_at timestamptz NOT NULL DEFAULT now());
CREATE INDEX IF NOT EXISTS memory_project_status_idx ON memory_items(project_id, status);
CREATE INDEX IF NOT EXISTS proposal_project_status_idx ON change_proposals(project_id, status);
